services:
  postgres:
    image: postgres:15-alpine
    container_name: codekids-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: codekids_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5555:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d codekids_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cron:
    image: oven/bun:1.1.34-alpine
    container_name: codekids-cron-dev
    restart: unless-stopped
    environment:
      - DB_URL=postgresql://postgres:postgres123@postgres:5432/codekids_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache curl &&
        bun install &&
        echo '0 */6 * * * cd /app && bun run cron:delete-verifications' > /etc/crontabs/root &&
        crond -f -l 2
      "

volumes:
  postgres_data_dev:
